// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace WiniumPOC.TestScenarios
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class UN281_SearchFileFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "UN281_SearchFile.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UN281_SearchFile", "\tSearch existing file sin Unity using Search File feature ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "UN281_SearchFile")))
            {
                global::WiniumPOC.TestScenarios.UN281_SearchFileFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TC001_MenuOptions_SearchFile_EndCustomer_LastName_FirstName")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UN281_SearchFile")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("completed")]
        public virtual void TC001_MenuOptions_SearchFile_EndCustomer_LastName_FirstName()
        {
            string[] tagsOfScenario = new string[] {
                    "completed"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC001_MenuOptions_SearchFile_EndCustomer_LastName_FirstName", null, new string[] {
                        "completed"});
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
testRunner.Given("Launch the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
testRunner.Then("in Unity main window click on \'Search\' submenu from \'Tools\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 8
testRunner.Then("in Search window click on \'End Customer\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
testRunner.Then("in End Customer tab enter value \'Chandran\' in the field \'LastName\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 10
testRunner.Then("in End Customer tab enter value \'Deepa\' in the field \'FirstName\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 11
testRunner.Then("in Search window click on \'Search\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 12
testRunner.Then("in End Customer tab click on \'Chandran\' value in search result table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 13
testRunner.Then("in Search window click on \'Ok\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 14
testRunner.Then("in the pop-up window click \'Ok\' for the message \'The dossier X120000206THA is ope" +
                        "ned by\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 15
testRunner.Then("in File Management window verify the value in the field \'Last\' is \'Chandran\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 16
testRunner.Then("in File Management window verify the value in the field \'First\' is \'Deepa\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
testRunner.Then("in Unity main window click on \'Release\' submenu from \'File\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TC002_Icon_SearchFile_EndCustomer_LicencePlate")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UN281_SearchFile")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("completed")]
        public virtual void TC002_Icon_SearchFile_EndCustomer_LicencePlate()
        {
            string[] tagsOfScenario = new string[] {
                    "completed"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC002_Icon_SearchFile_EndCustomer_LicencePlate", null, new string[] {
                        "completed"});
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 22
testRunner.Then("in Unity main window click on \'Search\' icon in the toolbar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
testRunner.Then("in Search window click on \'End Customer\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 24
testRunner.Then("in End Customer tab enter value \'12345\' in the field \'LicencePlate\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
testRunner.Then("in Search window click on \'Search\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 26
testRunner.Then("in End Customer tab click on \'12345\' value in search result table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 27
testRunner.Then("in Search window click on \'Ok\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
testRunner.Then("in File Management window verify the value in the field \'First\' is \'Deepa\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
testRunner.Then("in Unity main window click on \'Release\' submenu from \'File\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TC003_DatePicker")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UN281_SearchFile")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("completed")]
        public virtual void TC003_DatePicker()
        {
            string[] tagsOfScenario = new string[] {
                    "completed"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC003_DatePicker", null, new string[] {
                        "completed"});
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
testRunner.Given("Launch the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 34
testRunner.Then("in Unity main window click on \'Search\' icon in the toolbar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 36
testRunner.Then("in window select date \'01/01/2021\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TC004_MenuOptions_SearchFile_Country_LastName_FirstName_Country")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UN281_SearchFile")]
        public virtual void TC004_MenuOptions_SearchFile_Country_LastName_FirstName_Country()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC004_MenuOptions_SearchFile_Country_LastName_FirstName_Country", null, ((string[])(null)));
#line 38
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 39
testRunner.Given("Launch the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 40
testRunner.Then("in Unity main window click on \'Search\' submenu from \'Tools\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
testRunner.Then("in Search window click on \'Country\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 42
testRunner.Then("in Country tab enter value \'Test\' in the field \'LastName\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 43
testRunner.Then("in Country tab enter value \'Country\' in the field \'FirstName\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 44
testRunner.Then("in Country tab select value \'Turkey\' from the Country dropdown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
testRunner.Then("in Search window click on \'Search\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
testRunner.Then("in Country tab click on \'Test Country\' value in the column \'Surname and Name\' in " +
                        "search result table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
testRunner.Then("in Search window click on \'Ok\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
testRunner.Then("in the pop-up window click \'Ok\' for the message \'The dossier X120000206THA is ope" +
                        "ned by\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 49
testRunner.Then("in File Management window verify the value in the field \'Last\' is \'Test\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
testRunner.Then("in File Management window verify the value in the field \'First\' is \'Country\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
testRunner.Then("in File Management window verify the value in the field \'Country\' is \'Turkey\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
testRunner.Then("in Unity main window click on \'Release\' submenu from \'File\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TC005_Icon_SearchFile_File_Code")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UN281_SearchFile")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("need")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("to")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("verify")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("why")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("File")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tab")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("is")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("not")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("getting")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("clicked")]
        public virtual void TC005_Icon_SearchFile_File_Code()
        {
            string[] tagsOfScenario = new string[] {
                    "need",
                    "to",
                    "verify",
                    "why",
                    "File",
                    "tab",
                    "is",
                    "not",
                    "getting",
                    "clicked"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC005_Icon_SearchFile_File_Code", null, new string[] {
                        "need",
                        "to",
                        "verify",
                        "why",
                        "File",
                        "tab",
                        "is",
                        "not",
                        "getting",
                        "clicked"});
#line 55
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 56
testRunner.Given("Launch the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 57
testRunner.Then("in Unity main window click on \'Search\' icon in the toolbar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 58
testRunner.Then("in Search window click on \'File\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 60
testRunner.Then("in Search window enter the value \'X121000003THA\' in the field \'code\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 61
testRunner.Then("in Search window click on \'Search\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 62
testRunner.Then("in File Management window verify the value in the field \'File\' is \'X121000003THA\'" +
                        "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 63
testRunner.Then("in Unity main window click on \'Release\' submenu from \'File\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TC006_SearchFile_Claims_Search_ClaimNr_EndCustomer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UN281_SearchFile")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Executed")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("in")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("E1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("successfully")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("completed")]
        public virtual void TC006_SearchFile_Claims_Search_ClaimNr_EndCustomer()
        {
            string[] tagsOfScenario = new string[] {
                    "Executed",
                    "in",
                    "E1",
                    "successfully",
                    "completed"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC006_SearchFile_Claims_Search_ClaimNr_EndCustomer", null, new string[] {
                        "Executed",
                        "in",
                        "E1",
                        "successfully",
                        "completed"});
#line 67
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 68
testRunner.Given("Launch the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 69
testRunner.Then("in Unity main window click on \'Search\' submenu from \'Tools\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 70
testRunner.Then("in Search window click on \'Claims\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 71
testRunner.Then("in Claims tab enter the value \'Rojanasiri\' in the field \'endcustomerlastname\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
testRunner.Then("in Claims tab enter the value \'Aey\' in the field \'endcustomerfirstname\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 73
testRunner.Then("in Claims tab enter the value \'101\' in the field \'Comp\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 74
testRunner.Then("in Claims tab enter the value \'7\' in the field \'Progressive\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 75
testRunner.Then("in Claims tab enter the value \'12\' in the field \'Branch\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
testRunner.Then("in Search window click on \'Search\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 77
testRunner.Then("in Claims tab click on \'Rojanasiri Aey\' value in the column \'Surname and Name\' in" +
                        " search result table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 78
testRunner.Then("in Search window click on \'Ok\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 79
testRunner.Then("in File Management window click on \'Claims\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 80
testRunner.Then("in File Management window verify the value in the field \'Com\' is \'101\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 81
testRunner.Then("in File Management window verify the value in the field \'Prog\' is \'7\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 82
testRunner.Then("in File Management window verify the value in the field \'Bran\' is \'12\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
testRunner.Then("in File Management window verify the value in the field \'Last\' is \'Rojanasiri\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 84
testRunner.Then("in File Management window verify the value in the field \'First\' is \'Aey\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 85
testRunner.Then("in Unity main window click on \'Release\' submenu from \'File\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TC007_SearchFile_Claims_Search_ClaimNr_EndCustomer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UN281_SearchFile")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Execution")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("in")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("DWRemoval")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("failed")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("to")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("identify")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("the")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("claim")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("nr")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("fields")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("both")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("in")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("search")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("window")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("as")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("well")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("as")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("in")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FileManagement")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("window")]
        public virtual void TC007_SearchFile_Claims_Search_ClaimNr_EndCustomer()
        {
            string[] tagsOfScenario = new string[] {
                    "Execution",
                    "in",
                    "DWRemoval",
                    "failed",
                    "to",
                    "identify",
                    "the",
                    "claim",
                    "nr",
                    "fields",
                    "both",
                    "in",
                    "search",
                    "window",
                    "as",
                    "well",
                    "as",
                    "in",
                    "FileManagement",
                    "window"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC007_SearchFile_Claims_Search_ClaimNr_EndCustomer", null, new string[] {
                        "Execution",
                        "in",
                        "DWRemoval",
                        "failed",
                        "to",
                        "identify",
                        "the",
                        "claim",
                        "nr",
                        "fields",
                        "both",
                        "in",
                        "search",
                        "window",
                        "as",
                        "well",
                        "as",
                        "in",
                        "FileManagement",
                        "window"});
#line 88
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 89
testRunner.Given("Launch the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 90
testRunner.Then("in Unity main window click on \'Search\' submenu from \'Tools\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 91
testRunner.Then("in Search window click on \'Claims\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 92
testRunner.Then("in Claims tab enter the value \'ambe\' in the field \'endcustomerlastname\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 93
testRunner.Then("in Claims tab enter the value \'rash\' in the field \'endcustomerfirstname\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 94
testRunner.Then("in Claims tab enter the value \'12\' in the field \'Comp\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 95
testRunner.Then("in Claims tab enter the value \'9\' in the field \'Progressive\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
testRunner.Then("in Claims tab enter the value \'130\' in the field \'Branch\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 97
testRunner.Then("in Search window click on \'Search\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 98
testRunner.Then("in Claims tab click on \'ambe rash\' value in the column \'Surname and Name\' in sear" +
                        "ch result table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 99
testRunner.Then("in Search window click on \'Ok\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 100
testRunner.Then("in File Management window click on \'Claims\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 101
testRunner.Then("in File Management window verify the value in the field \'Com\' is \'12\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 102
testRunner.Then("in File Management window verify the value in the field \'Prog\' is \'9\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 103
testRunner.Then("in File Management window verify the value in the field \'Bran\' is \'130\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 104
testRunner.Then("in File Management window verify the value in the field \'Last\' is \'ambe\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 105
testRunner.Then("in File Management window verify the value in the field \'First\' is \'rash\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 106
testRunner.Then("in Unity main window click on \'Release\' submenu from \'File\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TC008_SearchFile_Claims_Search_EndCustomer")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UN281_SearchFile")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Completed")]
        public virtual void TC008_SearchFile_Claims_Search_EndCustomer()
        {
            string[] tagsOfScenario = new string[] {
                    "Completed"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC008_SearchFile_Claims_Search_EndCustomer", null, new string[] {
                        "Completed"});
#line 109
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 110
testRunner.Given("Launch the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 111
testRunner.Then("in Unity main window click on \'Search\' submenu from \'Tools\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 112
testRunner.Then("in Search window click on \'Claims\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 113
testRunner.Then("in Claims tab enter the value \'ambe\' in the field \'endcustomerlastname\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 114
testRunner.Then("in Claims tab enter the value \'rash\' in the field \'endcustomerfirstname\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 115
testRunner.Then("in Search window click on \'Search\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 116
testRunner.Then("in Claims tab click on \'ambe rash\' value in the column \'Surname and Name\' in sear" +
                        "ch result table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 117
testRunner.Then("in Search window click on \'Ok\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 118
testRunner.Then("in File Management window verify the value in the field \'Last\' is \'ambe\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 119
testRunner.Then("in File Management window verify the value in the field \'First\' is \'rash\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 120
testRunner.Then("in Unity main window click on \'Release\' submenu from \'File\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("TC009_SearchFile_MenuOptions_Merging_Tabs")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "UN281_SearchFile")]
        public virtual void TC009_SearchFile_MenuOptions_Merging_Tabs()
        {
            string[] tagsOfScenario = ((string[])(null));
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TC009_SearchFile_MenuOptions_Merging_Tabs", null, ((string[])(null)));
#line 122
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 123
testRunner.Given("Launch the Unity Application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 124
testRunner.Then("in Unity main window click on \'Search\' submenu from \'Tools\' main menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 125
testRunner.Then("check if \'Search\' window is opened", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 126
testRunner.Then("in Search window click on \'End Customer\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 127
testRunner.Then("in End Customer tab enter value \'testing\' in the field \'LastName\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 128
testRunner.Then("in Search window click on \'Include this tab in merged search\' checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 129
testRunner.Then("in Search window click on \'Claims\' tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 130
testRunner.Then("in Claims tab enter the value \'con\' in the field \'endcustomerfirstname\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 131
testRunner.Then("in Search window click on \'Include this tab in merged search\' checkbox", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 132
testRunner.Then("in Search window click on \'Search\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 133
testRunner.Then("in Claims tab verify if the values in the column \'Surname and Name\' contains \'tes" +
                        "ting con\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 134
testRunner.Then("in Search window click on \'Cancel\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
